/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack.view;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import pack.control.c_koneksi;
import pack.control.controllerToko;
import pack.model.m_toko;

/**
 *
 * @author Mokleters
 */
public class home extends javax.swing.JFrame {

    controllerToko cToko;
    List<m_toko>listdata = new ArrayList<>();
    
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        cToko = new controllerToko (this);
        cToko.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        admin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kodebarang = new javax.swing.JTextField();
        namabarang = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        kategoribarang = new javax.swing.JComboBox<>();
        jenispack = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        keluarbtn = new javax.swing.JButton();
        simpanbtn = new javax.swing.JButton();
        ubahbtn = new javax.swing.JButton();
        bersihbtn = new javax.swing.JButton();
        hapusbtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        carieuy = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(null);

        admin.setForeground(new java.awt.Color(0, 0, 0));
        admin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(admin);
        admin.setBounds(90, 10, 110, 30);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Admin Toko : ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 74, 16);

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DATA BARANG DI TOKO");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(190, 40, 430, 80);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 110);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setForeground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(null);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Harga :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 170, 100, 16);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Kode Barang :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 10, 100, 16);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nama Barang :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 50, 100, 16);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Kategori Barang :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 90, 100, 16);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Jenis Packaging : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 130, 100, 16);
        jPanel1.add(kodebarang);
        kodebarang.setBounds(140, 10, 390, 30);

        namabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namabarangActionPerformed(evt);
            }
        });
        jPanel1.add(namabarang);
        namabarang.setBounds(140, 50, 390, 28);
        jPanel1.add(harga);
        harga.setBounds(140, 170, 390, 28);

        kategoribarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Baranglain" }));
        jPanel1.add(kategoribarang);
        kategoribarang.setBounds(140, 90, 390, 26);

        jenispack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pack", "Unpack" }));
        jPanel1.add(jenispack);
        jenispack.setBounds(140, 130, 390, 26);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 110, 570, 210);

        jPanel3.setBackground(new java.awt.Color(51, 255, 204));
        jPanel3.setForeground(new java.awt.Color(51, 255, 204));
        jPanel3.setLayout(null);

        keluarbtn.setText("Keluar");
        keluarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarbtnActionPerformed(evt);
            }
        });
        jPanel3.add(keluarbtn);
        keluarbtn.setBounds(20, 170, 140, 28);

        simpanbtn.setText("Simpan");
        simpanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanbtnActionPerformed(evt);
            }
        });
        jPanel3.add(simpanbtn);
        simpanbtn.setBounds(20, 10, 140, 28);

        ubahbtn.setText("Ubah");
        ubahbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahbtnActionPerformed(evt);
            }
        });
        jPanel3.add(ubahbtn);
        ubahbtn.setBounds(20, 50, 140, 28);

        bersihbtn.setText("Bersihkan");
        bersihbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihbtnActionPerformed(evt);
            }
        });
        jPanel3.add(bersihbtn);
        bersihbtn.setBounds(20, 90, 140, 28);

        hapusbtn.setText("Hapus");
        hapusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbtnActionPerformed(evt);
            }
        });
        jPanel3.add(hapusbtn);
        hapusbtn.setBounds(20, 130, 140, 28);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(600, 110, 180, 210);

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setForeground(new java.awt.Color(51, 255, 204));
        jPanel4.setLayout(null);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode_Barang", "Nama_Barang", "Kategori", "Jenis", "Harga"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 550, 170);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(20, 360, 570, 190);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(null);
        getContentPane().add(jPanel5);
        jPanel5.setBounds(600, 360, 180, 190);

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setText("Pencarian berdasarkan kategori barang");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 330, 380, 20);

        carieuy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Baranglain" }));
        carieuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carieuyActionPerformed(evt);
            }
        });
        getContentPane().add(carieuy);
        carieuy.setBounds(350, 330, 160, 26);

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 318, 70, 40);

        setBounds(0, 0, 813, 596);
    }// </editor-fold>//GEN-END:initComponents

    private void namabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namabarangActionPerformed

    private void carieuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carieuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carieuyActionPerformed

    private void simpanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanbtnActionPerformed
        
        cToko.SimpanData();
        cToko.isiTable();

        // TODO add your handling code here:
    }//GEN-LAST:event_simpanbtnActionPerformed

    private void ubahbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahbtnActionPerformed
            
        cToko.Ubah();
        cToko.isiTable();

        // TODO add your handling code here:
    }//GEN-LAST:event_ubahbtnActionPerformed

    private void bersihbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihbtnActionPerformed
             
        cToko.Reset();
        // TODO add your handling code here:
    }//GEN-LAST:event_bersihbtnActionPerformed

    private void hapusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbtnActionPerformed
        
        cToko.Hapus();
        cToko.isiTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusbtnActionPerformed

    private void keluarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarbtnActionPerformed
            
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        cToko.CariKategori();
   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    
        String user1 = login.user;
        admin.setText(user1);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int baris = tabel.getSelectedRow();
         if (baris != -1) {
            kodebarang.setText(tabel.getValueAt(baris, 0).toString());
            namabarang.setText((String) tabel.getValueAt(baris, 1));
            kategoribarang.setSelectedItem(tabel.getValueAt(baris, 2).toString());
            jenispack.setSelectedItem(tabel.getValueAt(baris, 3).toString());
            harga.setText(tabel.getValueAt(baris, 4).toString());
            
        }
    }//GEN-LAST:event_tabelMouseClicked

    public JTextField getTxtKode(){
return kodebarang;
}
public JTextField getTxtNama(){
return namabarang;
}
public JTextField getTxtHarga(){
return harga;
}
public JComboBox getCbKategori(){
return kategoribarang;
}
public JComboBox getCbJenis(){
return jenispack;
}
public JComboBox getCbCariKategori(){
return carieuy;
}
public JButton getButtonHapus(){
return hapusbtn;
}
public JButton getButtonBersih(){
return bersihbtn;
}
public JButton getButtonSimpan(){
return simpanbtn;
}
public JButton getButtonUbah(){
return ubahbtn;
}
public JButton getButtonKeluar(){
return keluarbtn;
}
public JTable getTableData(){
return tabel;
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JButton bersihbtn;
    private javax.swing.JComboBox<String> carieuy;
    private javax.swing.JButton hapusbtn;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenispack;
    private javax.swing.JComboBox<String> kategoribarang;
    private javax.swing.JButton keluarbtn;
    private javax.swing.JTextField kodebarang;
    private javax.swing.JTextField namabarang;
    private javax.swing.JButton simpanbtn;
    private javax.swing.JTable tabel;
    private javax.swing.JButton ubahbtn;
    // End of variables declaration//GEN-END:variables
}


